import type { Grade, Question } from '../types/quiz';

export const SECRET_CODE = (import.meta.env.VITE_KEY ?? 'NOVA2026').trim().toUpperCase();

export const QUESTIONS: Question[] = [
  { id: 1, question: 'What is the capital of France?', options: ['Berlin', 'Madrid', 'Paris', 'Rome'], answer: 2 },
  { id: 2, question: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Saturn'], answer: 1 },
  { id: 3, question: 'What is 12 × 12?', options: ['132', '140', '144', '148'], answer: 2 },
  { id: 4, question: "Who wrote 'Romeo and Juliet'?", options: ['Charles Dickens', 'Mark Twain', 'William Shakespeare', 'Jane Austen'], answer: 2 },
  { id: 5, question: 'What is the chemical symbol for Gold?', options: ['Go', 'Gd', 'Au', 'Ag'], answer: 2 },
  { id: 6, question: 'How many continents are on Earth?', options: ['5', '6', '7', '8'], answer: 2 },
  { id: 7, question: 'What is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], answer: 3 },
  { id: 8, question: 'Which country invented the internet?', options: ['Japan', 'Germany', 'USA', 'UK'], answer: 2 },
  { id: 9, question: 'What gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'], answer: 2 },
  { id: 10, question: 'In what year did World War II end?', options: ['1943', '1944', '1945', '1946'], answer: 2 },
  { id: 11, question: 'What is the speed of light (approx)?', options: ['200,000 km/s', '299,792 km/s', '350,000 km/s', '150,000 km/s'], answer: 1 },
  { id: 12, question: 'Which element has atomic number 1?', options: ['Helium', 'Hydrogen', 'Lithium', 'Carbon'], answer: 1 },
  { id: 13, question: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], answer: 1 },
  { id: 14, question: 'What is the hardest natural substance on Earth?', options: ['Ruby', 'Iron', 'Diamond', 'Quartz'], answer: 2 },
  { id: 15, question: 'Who painted the Mona Lisa?', options: ['Van Gogh', 'Picasso', 'Leonardo da Vinci', 'Michelangelo'], answer: 2 },
  { id: 16, question: 'What is the tallest mountain in the world?', options: ['K2', 'Kangchenjunga', 'Lhotse', 'Mount Everest'], answer: 3 },
  { id: 17, question: 'How many bones are in the adult human body?', options: ['196', '206', '216', '226'], answer: 1 },
  { id: 18, question: 'Which country is the largest by area?', options: ['China', 'USA', 'Canada', 'Russia'], answer: 3 },
  { id: 19, question: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi Body'], answer: 2 },
  { id: 20, question: 'What language has the most native speakers?', options: ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'], answer: 2 },
  { id: 21, question: 'Which animal is the fastest on land?', options: ['Lion', 'Cheetah', 'Horse', 'Greyhound'], answer: 1 },
  { id: 22, question: 'What is the square root of 256?', options: ['14', '15', '16', '17'], answer: 2 },
  { id: 23, question: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], answer: 1 },
  { id: 24, question: 'What is the national currency of Japan?', options: ['Won', 'Yuan', 'Yen', 'Baht'], answer: 2 },
  { id: 25, question: 'Who developed the theory of relativity?', options: ['Newton', 'Tesla', 'Einstein', 'Bohr'], answer: 2 },
  { id: 26, question: 'What is the longest river in the world?', options: ['Amazon', 'Yangtze', 'Mississippi', 'Nile'], answer: 3 },
  { id: 27, question: 'How many colors are in a rainbow?', options: ['5', '6', '7', '8'], answer: 2 },
  { id: 28, question: 'What organ pumps blood through the body?', options: ['Lungs', 'Liver', 'Kidney', 'Heart'], answer: 3 },
  { id: 29, question: 'In which continent is Egypt located?', options: ['Asia', 'Europe', 'Africa', 'Middle East'], answer: 2 },
  { id: 30, question: 'What is the freezing point of water in Celsius?', options: ['-1°C', '0°C', '1°C', '4°C'], answer: 1 },
  { id: 31, question: 'Which planet has the most moons?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], answer: 1 },
  { id: 32, question: 'What year was the first iPhone released?', options: ['2005', '2006', '2007', '2008'], answer: 2 },
  { id: 33, question: "Who wrote '1984'?", options: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells'], answer: 1 },
  { id: 34, question: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Brisbane', 'Canberra'], answer: 3 },
  { id: 35, question: 'How many teeth does an adult human have?', options: ['28', '30', '32', '34'], answer: 2 },
  { id: 36, question: 'What does DNA stand for?', options: ['Deoxyribonucleic Acid', 'Double Nucleic Acid', 'Dioxygenated Nucleic Acid', 'Dynamic Nucleic Arrangement'], answer: 0 },
  { id: 37, question: 'Which sport uses a shuttlecock?', options: ['Tennis', 'Squash', 'Badminton', 'Pickleball'], answer: 2 },
  { id: 38, question: 'How many hours are in a week?', options: ['148', '160', '168', '172'], answer: 2 },
  { id: 39, question: 'What is the capital of Brazil?', options: ['Rio de Janeiro', 'Sao Paulo', 'Salvador', 'Brasilia'], answer: 3 },
  { id: 40, question: "What is the most abundant gas in Earth's atmosphere?", options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'], answer: 2 },
  { id: 41, question: 'Who invented the telephone?', options: ['Nikola Tesla', 'Thomas Edison', 'Alexander Graham Bell', 'Guglielmo Marconi'], answer: 2 },
  { id: 42, question: 'What is the smallest country in the world?', options: ['Monaco', 'San Marino', 'Liechtenstein', 'Vatican City'], answer: 3 },
  { id: 43, question: 'Which programming language is named after a coffee?', options: ['Python', 'Java', 'Ruby', 'Swift'], answer: 1 },
  { id: 44, question: 'What is the boiling point of water in Fahrenheit?', options: ['200°F', '212°F', '220°F', '230°F'], answer: 1 },
  { id: 45, question: 'How many strings does a standard guitar have?', options: ['4', '5', '6', '7'], answer: 2 },
  { id: 46, question: 'What is the largest desert in the world?', options: ['Sahara', 'Arabian', 'Gobi', 'Antarctic'], answer: 3 },
  { id: 47, question: 'Who invented the light bulb?', options: ['Tesla', 'Bell', 'Edison', 'Faraday'], answer: 2 },
  { id: 48, question: 'What is the symbol for Potassium on the periodic table?', options: ['Po', 'Pt', 'K', 'Ka'], answer: 2 },
  { id: 49, question: 'What is 7 factorial (7!)?', options: ['2040', '5040', '720', '40320'], answer: 1 },
  { id: 50, question: 'Which animal has the longest lifespan?', options: ['Tortoise', 'Elephant', 'Bowhead Whale', 'Greenland Shark'], answer: 3 },
  { id: 51, question: 'What does HTTP stand for?', options: ['HyperText Transfer Protocol', 'High Transfer Text Protocol', 'HyperText Transport Program', 'Hybrid Text Transfer Protocol'], answer: 0 },
  { id: 52, question: 'How many valence electrons does Carbon have?', options: ['2', '3', '4', '6'], answer: 2 },
  { id: 53, question: 'What is the name of the galaxy we live in?', options: ['Andromeda', 'Triangulum', 'Milky Way', 'Whirlpool'], answer: 2 },
  { id: 54, question: 'Which country is known as the Land of the Rising Sun?', options: ['China', 'South Korea', 'Japan', 'Vietnam'], answer: 2 },
  { id: 55, question: 'What is the most spoken language in the world?', options: ['English', 'Mandarin Chinese', 'Spanish', 'Arabic'], answer: 1 },
  { id: 56, question: 'How many chambers does the human heart have?', options: ['2', '3', '4', '5'], answer: 2 },
  { id: 57, question: 'What is the sum of angles in a triangle?', options: ['90°', '160°', '180°', '270°'], answer: 2 },
  { id: 58, question: 'Which element is a liquid at room temperature (besides mercury)?', options: ['Bromine', 'Gallium', 'Cesium', 'Francium'], answer: 0 },
  { id: 59, question: 'Who was the first person to walk on the moon?', options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn'], answer: 2 },
  { id: 60, question: 'What year did the Berlin Wall fall?', options: ['1987', '1988', '1989', '1990'], answer: 2 },
  { id: 61, question: 'What is the main ingredient in guacamole?', options: ['Tomato', 'Lime', 'Avocado', 'Onion'], answer: 2 },
  { id: 62, question: 'How many players are on a basketball team on the court?', options: ['4', '5', '6', '7'], answer: 1 },
  { id: 63, question: "What does 'www' stand for in a website URL?", options: ['World Wide Web', 'World Web Wide', 'Wide World Web', 'Web World Wide'], answer: 0 },
  { id: 64, question: 'What is the currency of the United Kingdom?', options: ['Euro', 'Dollar', 'Pound Sterling', 'Franc'], answer: 2 },
  { id: 65, question: 'Which planet is closest to the Sun?', options: ['Venus', 'Earth', 'Mercury', 'Mars'], answer: 2 },
  { id: 66, question: 'How many keys does a standard piano have?', options: ['76', '80', '84', '88'], answer: 3 },
  { id: 67, question: 'What is the chemical formula for water?', options: ['HO', 'H2O', 'H3O', 'HO2'], answer: 1 },
  { id: 68, question: 'Who painted the Sistine Chapel ceiling?', options: ['Raphael', 'Donatello', 'Leonardo', 'Michelangelo'], answer: 3 },
  { id: 69, question: 'What is the most downloaded app of all time?', options: ['Facebook', 'YouTube', 'TikTok', 'Instagram'], answer: 2 },
  { id: 70, question: 'How many legs does a spider have?', options: ['6', '7', '8', '10'], answer: 2 },
  { id: 71, question: 'Which country has the most natural lakes?', options: ['USA', 'Russia', 'Finland', 'Canada'], answer: 3 },
  { id: 72, question: 'What is the rarest blood type?', options: ['A negative', 'B negative', 'O negative', 'AB negative'], answer: 3 },
  { id: 73, question: 'How many zeros are in one billion?', options: ['7', '8', '9', '10'], answer: 2 },
  { id: 74, question: 'Which Shakespeare play features Hamlet?', options: ['Othello', 'Macbeth', 'Hamlet', 'King Lear'], answer: 2 },
  { id: 75, question: 'What is the unit of electrical resistance?', options: ['Volt', 'Ampere', 'Ohm', 'Watt'], answer: 2 },
  { id: 76, question: 'Which country hosted the 2016 Summer Olympics?', options: ['China', 'UK', 'Brazil', 'Japan'], answer: 2 },
  { id: 77, question: 'How many minutes are in a day?', options: ['1220', '1380', '1440', '1560'], answer: 2 },
  { id: 78, question: 'What is the largest internal organ in the human body?', options: ['Heart', 'Brain', 'Liver', 'Kidney'], answer: 2 },
  { id: 79, question: 'Which element is a noble gas?', options: ['Fluorine', 'Chlorine', 'Neon', 'Nitrogen'], answer: 2 },
  { id: 80, question: 'What does AI stand for?', options: ['Automated Intelligence', 'Artificial Intelligence', 'Advanced Integration', 'Autonomous Interface'], answer: 1 },
  { id: 81, question: 'How many chromosomes do humans have?', options: ['44', '46', '48', '50'], answer: 1 },
  { id: 82, question: 'Which country is the Eiffel Tower in?', options: ['Italy', 'Spain', 'Belgium', 'France'], answer: 3 },
  { id: 83, question: 'What is the closest star to Earth?', options: ['Sirius', 'Alpha Centauri', 'The Sun', 'Proxima Centauri'], answer: 2 },
  { id: 84, question: 'What is photosynthesis?', options: ['Cell division process', 'Digestion in plants', 'Converting sunlight to energy', 'Plant respiration'], answer: 2 },
  { id: 85, question: 'Which ocean is the smallest?', options: ['Indian', 'Southern', 'Arctic', 'Atlantic'], answer: 2 },
  { id: 86, question: 'What does CPU stand for?', options: ['Central Process Unit', 'Computer Processing Unit', 'Central Processing Unit', 'Core Processing Utility'], answer: 2 },
  { id: 87, question: 'Who founded Microsoft?', options: ['Steve Jobs', 'Mark Zuckerberg', 'Bill Gates', 'Jeff Bezos'], answer: 2 },
  { id: 88, question: 'What is the national animal of India?', options: ['Lion', 'Elephant', 'Bengal Tiger', 'Snow Leopard'], answer: 2 },
  { id: 89, question: 'How many planets in our solar system have rings?', options: ['1', '2', '3', '4'], answer: 3 },
  { id: 90, question: 'What language is spoken in Brazil?', options: ['Spanish', 'Portuguese', 'French', 'Brazilian'], answer: 1 },
  { id: 91, question: 'What is the value of Pi (to 2 decimal places)?', options: ['3.12', '3.14', '3.16', '3.18'], answer: 1 },
  { id: 92, question: 'Which vitamin is produced when skin is exposed to sunlight?', options: ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], answer: 3 },
  { id: 93, question: 'What is the largest mammal on Earth?', options: ['African Elephant', 'Giraffe', 'Blue Whale', 'Sperm Whale'], answer: 2 },
  { id: 94, question: 'How many sides does an octagon have?', options: ['6', '7', '8', '9'], answer: 2 },
  { id: 95, question: 'What country has the most pyramids?', options: ['Egypt', 'Mexico', 'Sudan', 'Peru'], answer: 2 },
  { id: 96, question: 'Which planet has the Great Red Spot?', options: ['Saturn', 'Neptune', 'Uranus', 'Jupiter'], answer: 3 },
  { id: 97, question: 'What is binary code based on?', options: ['Base 8', 'Base 2', 'Base 10', 'Base 16'], answer: 1 },
  { id: 98, question: 'Who invented gravity (described it)?', options: ['Einstein', 'Galileo', 'Newton', 'Kepler'], answer: 2 },
  { id: 99, question: 'What is the chemical symbol for Iron?', options: ['Ir', 'In', 'Fe', 'Fr'], answer: 2 },
  { id: 100, question: 'What is the most recycled material in the world?', options: ['Plastic', 'Paper', 'Glass', 'Steel'], answer: 3 },
];

export const OPTION_LABELS = ['A', 'B', 'C', 'D', 'E'];

export const GRADE_COLORS: Record<Grade, string> = {
  S: '#ffd700',
  A: '#00e5ff',
  B: '#69ff47',
  C: '#ff9800',
  D: '#ff5722',
  F: '#f44336',
};
